[package]
name = "reader"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = { version = "0.24", features = ["dates"] }


[lib]
name = "reader"         # this will produce mydll.dll
crate-type = ["cdylib"]  # cdylib = C-compatible dynamic library
path = "src/reader.rs"